name: brevly

services:
  pg:
    container_name: brevly.postgres
    image: bitnami/postgresql:14.15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
